### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by norpchen** [sparkfun/Triple_Axis_Magnetometer-HMC5883L#1]
HMC5883L.h is missing from this repository?  It's referenced in the sample code, but nowhere to be found...

Thanks

**Comment by ToniCorinne** [comment]
Hi @norpchen - you need to download the appropriate library from the original author [here](https://github.com/manifestinteractive/arduino/tree/master/Libraries/HMC5883L). Once you install that library into your Arduino IDE, you should be able to run the sketch without issue.
